## This is example of Docker Compose for ReportPortal
## Do not forget to configure data volumes for production usage

## Execute 'docker-compose -f docker-compose.yml -p reportportal up -d --force-recreate' --build
## to start all containers in daemon mode
## Where:
##      '-f docker-compose.yml' -- specifies this compose file
##      '-p reportportal' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '2.4'
services:

  server-migration:
    image: reportportal/server-migration:latest
    environment:
      # Postgres params
      RP_DB_HOST: postgres
#      RP_DB_USER: rpuser
#      RP_DB_PASS: rppass
#      RP_DB_NAME: reportportal
#      RP_DB_PORT: 5432

      RP_BINARYSTORE_TYPE: minio
      RP_BINARYSTORE_MINIO_ENDPOINT: http://minio:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY: minio
      RP_BINARYSTORE_MINIO_SECRETKEY: minio123

      ## Users last login date older than ISO_LOCAL_DATE (yyyy-MM-dd) will not migrate
      RP_USER_KEEPFROM: '2000-01-01'

      # Mongodb params
      RP_MONGODB_DATABASE: reportportal
      RP_MONGODB_URI: mongodb://user:password@host:port