spring:
  data:
    mongodb:
      host: ${rp.mongodb.host}
      port: ${rp.mongodb.port}
      database: ${rp.mongodb.database}
      username: ${rp.mongodb.user}
      password: ${rp.mongodb.pass}

rp:
  mongodb:
    host: dev.epm-rpp.projects.epam.com
    port: 27017
    database: reportportal
    user: ${null}
    pass: ${null}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: ${rp.db.url}
    username: ${rp.db.user}
    password: ${rp.db.pass}
    maximumPoolSize: 50

  db:
    url: jdbc:postgresql://${rp.db.host}:${rp.db.port}/${rp.db.name}
    name: reportportal
    host: localhost
    port: 5432
    user: rpuser
    pass: rppass

  binarystore:
    path: /data/storage
    conatiner:
      path: /data/storage
    master:
      host: seaweed-master
      port: 9333
    minio:
      endpoint: http://play.min.io
      accessKey: default
      secretKey: default
    # could be one of [seaweed, filesystem, minio]
    type: filesystem

  ##keep launches from date in ISO_LOCAL_DATE (yyyy-MM-dd)
  launch:
    keepFrom: 2019-03-30
  test:
    keepFrom: 2019-03-30
  log:
    keepFrom: 2019-03-30
  attach:
    keepFrom: 2019-03-30
  user:
    keepFrom: 2019-03-30


logging:
  level:
    root: info
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

